mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('quizz.urls')),
]

quizz/urls.py
from django.urls import path
from .views import home, signup, ready_to_test,\
    test, check_test, new_question, new_test, profile


urlpatterns = [
    path('', home, name='home'),
    path('signup/', signup, name='signup'),
    path('<int:test_id>/ready-to-test/', ready_to_test, name='ready_to_test'),
    path('<int:test_id>/test/', test, name='test'),
    path('<int:check_test_id>/check-test/', check_test, name='check_test'),
    path('new-test/', new_test, name='new_test'),
    path('<int:test_id>/new-question/', new_question, name='new_question'),
    path('<int:user_id>/profile', profile, name='profile')
]

quizz/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now, timedelta
from django.dispatch import receiver
from django.db.models.signals import pre_save

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Test(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    max_attemps = models.PositiveIntegerField()
    pass_percentage = models.PositiveIntegerField(default=0)
    start_date = models.DateTimeField(default=now)
    end_date = models.DateTimeField(now()+timedelta(days=7))
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-start_date']
        indexes = [
            models.Index(fields=['-start_date'])
        ]

    def __str__(self):
        return self.title


class Question(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    question = models.CharField(max_length=500)
    a = models.CharField(max_length=255)
    b = models.CharField(max_length=255)
    c = models.CharField(max_length=255)
    d = models.CharField(max_length=255)
    true_answer = models.CharField(max_length=255, help_text="E.x: a")

    def __str__(self):
        return self.question


class CheckTest(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    finded_question = models.PositiveIntegerField(default=0)
    user_passed = models.BooleanField(default=False)
    percentage = models.PositiveBigIntegerField(default=0)

    def __str__(self):
        return self.student.username


class CheckQuestion(models.Model):
    check_test = models.ForeignKey(CheckTest, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    given_answer = models.CharField(max_length=1, help_text="E.x: a")
    true_answer = models.CharField(max_length=1, help_text="E.x: a")
    is_true = models.BooleanField(default=False)


@receiver(pre_save, sender=CheckQuestion)
def check_answer(sender, instance, *args, **kwargs):
    if instance.given_answer == instance.true_answer:
        instance.true_answer = True


@receiver(pre_save, sender=CheckTest)
def check_test(sender, instance, *args, **kwargs):
    checktest = instance
    checktest.finded_question = CheckQuestion.objects.filter(
        check_test=checktest, is_true=True).count()
    try:
        checktest.percentage = (
            checktest.finded_question / checktest.test.question_set.count()) * 100
        if checktest.test.pass_percentage <= checktest.percentage:
            checktest.user_passed = True
    except:
        pass

quizz/forms.py
from django import forms
from .models import Question, Test


class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ('category', 'title', 'max_attemps', 'pass_percentage', 'start_date', 'end_date')

    def save(self, request, comment=True):
        test = self.instance
        test.author = request.user
        super().save(comment)
        return test.id


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'
    submit_and_exit = forms.BooleanField(required=False)

    def save(self, test_id, comment=True):
        question = self.instance
        question.test = Test.objects.get(id=test_id)
        super().save(comment)
        return question

quizz/views.py
from django.utils import timezone
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from quizz.forms import QuestionForm, TestForm
from .models import CheckQuestion, CheckTest, Question, Test
from django.contrib.auth.decorators import login_required
# from .forms import QuestionForm, TestForm

# Create your views here.


def home(request):
    tests = Test.objects.all()
    return render(request, 'index.html', {
        'tests': tests
    })


# signup
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(home)
        else:
            print(form.errors)
    form = UserCreationForm()
    return render(request, 'registration/signup.html', {
        'form': form
    })

# profile


@login_required(login_url='login')
def profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    return render(request, 'profile.html', {
        'user': user
    })


@login_required(login_url='login')
def ready_to_test(request, test_id):
    test = get_object_or_404(Test, id=test_id)
    return render(request, 'ready_to_test.html', {
        'test': test
    })


@login_required(login_url='login')
def test(request, test_id):
    test = get_object_or_404(Test, id=test_id)
    attemps = CheckTest.objects.filter(student=request.user, test=test).count()
    if attemps <= test.max_attemps and (timezone.now() >= test.start_date and timezone.now() <= test.end_date):
        questions = Question.objects.filter(test=test)
        if request.method == 'POST':
            check_test = CheckTest.objects.create(
                student=request.user, test=test)
            for question in questions:
                given_answer = request.POST[str(question.id)]
                print(given_answer+'\n')
                CheckQuestion.objects.create(
                    check_test=check_test,
                    question=question,
                    given_answer=given_answer,
                    true_answer=question.true_answer)
            check_test.save()
            return redirect('check_test', check_test.id)
        return render(request, 'test.html', {
            'test': test,
            'questions': questions
        })
    else:
        print(attemps)
        return HttpResponse("Server Error")


@login_required(login_url='login')
def check_test(request, check_test_id):
    check_test = get_object_or_404(
        CheckTest, id=check_test_id, student=request.user)
    print(check_test)
    return render(request, 'check_test.html', {
        'check_test': check_test
    })


@login_required(login_url='login')
def new_test(request):
    if request.method == 'POST':
        form = TestForm(request.POST)
        if form.is_valid():
            test_id = form.save(request)
            return redirect('new_question', test_id)
    form = TestForm()
    return render(request, 'new_test.html', {
        'form': form
    })


@login_required(login_url='login')
def new_question(request, test_id):
    test = get_object_or_404(Test, id=test_id)
    if test.author == request.user:
        if request.method == 'POST':
            form = QuestionForm(request.POST)
            if form.is_valid():
                form.save(test_id)
                if form.cleaned_data['submit_and_exit']:
                    return redirect('home')
                return redirect('new_question', test_id)
        form = QuestionForm()
        return render(request, 'new_question.html', {
            'test': test,
            'form': form
        })
    else:
        return HttpResponse("Server Error")

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
            crossorigin="anonymous"
        />
        <title>{% block title %}{% endblock title %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
            <a class="navbar-brand" href="#">Quizz website</a>
            <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="offcanvas"
                data-bs-target="#navbarOffcanvasLg"
                aria-controls="navbarOffcanvasLg"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div
                class="offcanvas offcanvas-end"
                tabindex="-1"
                id="navbarOffcanvasLg"
                aria-labelledby="navbarOffcanvasLgLabel"
            >
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="#">Add Test</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  {% if  request.user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="#">Profile</a>
                </li>
                 {% endif %}
                </ul>
            </div>
        </nav>
        When using offcanvas in a dark navbar, be aware that you may need to have a dark background on the offcanvas
        content to avoid the text becoming illegible. In the example below, we add .navbar-dark and .bg-dark to the
        .navbar, .text-bg-dark to the .offcanvas, .dropdown-menu-dark to .dropdown-menu, and .btn-close-white to
        .btn-close for proper styling with a dark offcanvas. Offcanvas dark navbar HTML

        <nav class="navbar navbar-dark bg-dark fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Quizz website</a>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="offcanvas"
                    data-bs-target="#offcanvasDarkNavbar"
                    aria-controls="offcanvasDarkNavbar"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div
                    class="offcanvas offcanvas-end text-bg-dark"
                    tabindex="-1"
                    id="offcanvasDarkNavbar"
                    aria-labelledby="offcanvasDarkNavbarLabel"
                >
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Quizz website</h5>
                        <button
                            type="button"
                            class="btn-close btn-close-white"
                            data-bs-dismiss="offcanvas"
                            aria-label="Close"
                        ></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="#">Home</a>
                            </li>
                            {% if request.user.is_authenticated %}
                            <li class="nac-item">
                                <a href="{% url 'profile' request.user.id %}" class="nav-link">
                                    Profile
                                </a>
                            </li>
                            <li class="nac-item">
                                <a href="{% url 'new_test' %}" class="nav-link">
                                   Add test
                                </a>
                            </li>
                            <li class="nac-item">
                                <a href="#" class="nav-link">
                                    <button type="button" class="btn btn-info">{{ request.user.username }}</button>
                                </a>
                            </li>
                            <li class="nac-item">
                                <a href="{% url 'logout' %}" class="nav-link">
                                    <button type="button" class="btn btn-danger">Logout</button>
                                </a>
                            </li>
                            {% else %}
                            <li class="nac-item">
                                <a href="{% url 'login' %}" class="nav-link">
                                    <button type="button" class="btn btn-warning">Login</button>
                                </a>
                            </li>
                            <li class="nac-item">
                                <a href="{% url 'signup' %}" class="nav-link">
                                    <button type="button" class="btn btn-primary">Sign Up</button>
                                </a>
                            </li>

                            {% endif %}
                        </ul>
                        <form class="d-flex mt-3" role="search">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                            <button class="btn btn-success" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
        <main>
            <div class="container">
                    {% block content %}{% endblock content %}
            </div>
        </main>
        <footer>
            <div class="footer m-5 mb-3">
                <center class="text-muted">
                        Mahmudjonov Nurillo | 2023
                </center>
            </div>
        </footer>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
            integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
            integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

templates/check_test.html
{% extends 'base.html' %} {% block title %}Check Answer{% endblock title %} {% block content %}
<div class="content mt-5">
    <center>
        {% if Check_test.user_passed %}
        <h1>You have successfully passed the test</h1>
        {% else %}
        <h1>You have to solve {{check_test.test.pass_percentage}} of the test all least</h1>
        {% endif %}

        <h2 class="mb-4">You finded {{ check_test.percentage }} of all questions</h2>
    </center>
    <div class="card" p-3>
        {% for question in check_test.checkquestion_set.all %}
        <h5>{{forloop.counter}}. {{question.question}}</h5>
        {% if question.is_true %}
        <div class="answer p-2">
            <p>Note:<span>{{question.given_answer}}</span> was marked</p>
            <p>A: {{question.question.a}}</p>
            <p>B: {{question.question.b}}</p>
            <p>C: {{question.question.c}}</p>
            <p>D: {{question.question.d}}</p>
        </div>
        {%else%}
        <div class="answer p-2" style="background-color: rgba(255, 129, 129, 0.39)">
            <p>Note: <span>{{question.given_answer}}</span> was marked</p>
            <p>A: {{question.question.a}}</p>
            <p>B: {{question.question.b}}</p>
            <p>C: {{question.question.c}}</p>
            <p>D: {{question.question.d}}</p>
            <p></p>
            <p>Correct Answer: {{question.question.true_answer}}</p>
        </div>
        {% endif %} {% endfor %}
        <a href="{% url 'home' %}" class="btn btn-primary mt-2">Back home</a>
    </div>
</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %} {% block title %}Login{% endblock title %} {% block content %}
<div class="container">
    <div class="content mt-3">
        <h2>Lastest Tests for you</h2>
        <ol>
            {% for test in tests %}
            <li>
                <small>
                    <a href="{% url 'ready_to_test' test.id %}">Try it</a>
                </small>
            </li>
            {% endfor %}
        </ol>
    </div>
</div>
{% endblock content %}

templates/new_question.html
{% extends 'base.html' %} {% block title %} New question for {{test}}{% endblock title %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-8 mt-5">
            <h2>New question for {{test}}</h2>
            <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{% url 'home' %}" class="btn btn-primary">Back Home</a>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock content %}

templates/new_test.html
{% extends 'base.html' %} {% block title %} New Test {% endblock title %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-8 mt-5">
            <h2>New question for {{test}}</h2>
            <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{% url 'home' %}" class="btn btn-primary">Back Home</a>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock content %}

templates/profile.html
{% extends 'base.html' %} {% block title %}Profile {% endblock title%} {% block content %}
<div class="container">
    <div class="content mt-3">
        <h3>Profile - {{user}}</h3>
        <div class="row">
            <div class="card p-2 col-5 m-4">
                <h2>Created Tests</h2>
                {% for test in user.test_set.all %}
                <p>{{test.title}}</p>
                <small class="d-inline">
                    {{test.checktest_set.all.count}} attemps | {{test.question_set.all.count}} questions <br />
                    {% if test.checktest_set.all.count is not test.question_set.all.count %}
                    <a href="{% url 'ready_to_test' test.id %}">try</a>
                    {% endif %} {% if user is request.user %}
                    <a href="{% url 'new_question' test.id %}">Add question</a>
                    {% endif %}
                </small>
                <hr />
                {% endfor %}
            </div>
            <div class="card p-2 col-5 m-4">
                <h2>Attended Tests</h2>
                {% for i in user.checktest_set.all%}
                <p>{{i.title}}</p>
                <small class="d-inline">
                    <a href="{% url 'check_test' i.id%}">details</a> | {{i.percentage}} |
                    <a href="{% url 'ready_to_test' i.test.id%}">Try again</a>
                </small>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/ready_to_test.html
{% extends 'base.html' %} {% block title %}Ready to Test{% endblock title %} {% block content %}
<div class="content mt-5">
    <h3>Are you ready testing | Test title: {{ test.title }}</h3>
    <p>
        Details: There are <strong>{{ test.question.all.count }}</strong> questions. <br />
        You have total <strong>{{ test.max_attemps }}</strong> attemps.
    </p>
    <p>
        Make sure this whole test time is inside of <strong>{{ test.start_date}}</strong> and
        <strong>{{ test.end_date}}</strong>
    </p>
    {% comment %}
    <p>Author: <a href="{% url 'profile' test.author.id%}">@{{ test.author.username }}</a></p>
    {% endcomment %}
    <a href="{% url 'test' test.id%}" class="btn btn-primary">Start test</a>
    <a href="{% url 'home' %}" class="btn btn-secondary">Back</a>
</div>
{% endblock content %}

templates/test.html
{% extends 'base.html' %} {% block title %}Test Page{% endblock title %} {% block content %}
<div class="container">
    <h3>{{test.title}}</h3>
    <form action="" class="card p-3" method="post">
        {% csrf_token %}
        <div class="form-group">
            {% for question in questions %}
            <h5>{{forloop.counter }}: {{ question.question }}</h5>
            <div class="form-check form-check-inline">
                <input
                    class="form-check-input"
                    type="radio"
                    required
                    name="{{question.id}}"
                    id="{{question.id}}-a"
                    value="
                    a"
                />
                <label for="{{question.id}}-a">{{ question.a }}</label>
                <br />
                <input class="form-check-input" type="radio" name="{{question.id}}" id="{{question.id}}-b" value="b" />
                <label for="{{question.id}}-b">{{ question.b}}</label>
                <br />
                <input class="form-check-input" type="radio" name="{{question.id}}" id="{{question.id}}-c" value="c" />
                <label for="{{question.id}}-c">{{ question.c }}</label>
                <br />
                <input class="form-check-input" type="radio" name="{{question.id}}" id="{{question.id}}-d" value="d" />
                <label for="{{question.id}}-d">{{ question.d }}</label>
                <br />
            </div>
            <hr />
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit">Check your answers</button>
        </div>
    </form>
</div>

{% endblock content%}